### ISSUE TITLE
[TODO]: Investigate Smile port configurability

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/python-plugwise#677]
### Todo

As discussed in https://github.com/home-assistant/core/pull/132878 and on discord between various parties, investigate changeability for port in HA-Core. For now (regarding the linked PR) we decided **not** to remove from the manual configure flow but **not introduce** the option via reconfigure until we are sure about (list including but not limited to the below, feel free to add):

- [x] Default port (configuration indicates 80)
- [x] Defacto zeroconf port (is this 80 or 443)
- [ ] Investigate 443 usage (self-signed 2037 lapsing on non-legacy, not sure about legacy)
- [ ] Percentage of users changing their port by DMZ- or NATing there configuration in another subnet or VLAN

cc @bouwew @joostlek

**Comment by bouwew** [comment]
Looks like I can connected to my Adam via `https://<ip-address>:443/` next to `http://<ip-address>/`

**Comment by CoMPaTech** [comment]
Yup, because it is self-signed and expires 2037 (which both are more-or-less red flags to browser(libraries) nowadays. And not sure if a device becomes legacy if we could still support it. I do encourage TLS over plain, though it could be tricky in the future. We should re-check what zeroconf sees/advertises I guess.

**Comment by CoMPaTech** [comment]
Zeroconf advertises 80 - so I guess we should stick to 80 and consider dropping port configuration?

```
Service Plugwise on smileREDACTED._plugwise._tcp.local. of type _plugwise._tcp.local. state changed: ServiceStateChange.Added
Info from zeroconf.get_service_info: ServiceInfo(type='_plugwise._tcp.local.', name='Plugwise on smileREDACTED._plugwise._tcp.local.', addresses=[], port=80, weight=0, priority=0, server='smileREDACTED.local.', properties={b'product': b'smile_thermo', b'version': b'4.4.1', b'path': b'/', b'status': b'/system'}, interface_index=None)
  Addresses: fe80::d60f:REDACTED%15:80
  Weight: 0, priority: 0
  Server: smileREDACTED.local.
  Properties are:
    b'product': b'smile_thermo'
    b'version': b'4.4.1'
    b'path': b'/'
    b'status': b'/system'


Service Web Server on smileREDACTED._http._tcp.local. of type _http._tcp.local. state changed: ServiceStateChange.Added
Info from zeroconf.get_service_info: ServiceInfo(type='_http._tcp.local.', name='Web Server on smileREDACTED._http._tcp.local.', addresses=[], port=80, weight=0, priority=0, server='smileREDACTED.local.', properties={b'path': b'/'}, interface_index=None)
  Addresses: fe80::c693REDACTED%15:80
  Weight: 0, priority: 0
  Server: smileREDACTED.local.
  Properties are:
    b'path': b'/'
```

**Comment by bouwew** [comment]
Implemented in pw-beta v0.57.0

**Comment by CoMPaTech** [comment]
Since this was a core issue - I suggest we leave this open until followed up by a Core PR

**Comment by bouwew** [comment]
Part of HA Core now, closed.
